import Navbar from "@/components/Navbar";
import "./globals.css";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer";
import classNames from "@/utils/classNames";
import Providers from "@/providers/Providers";
import Toaster from "@/components/Toaster";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark" className="transition-all" lang="en">
      <body
        className={classNames(
          roboto.variable,
          "container mx-auto px-2 font-Roboto"
        )}
      >
        <Providers>
          <div className="flex flex-col min-h-screen justify-between">
            <div>
              <Navbar />
              <main className="mt-5">{children}</main>
            </div>
            <Footer />
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
